### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by mcintyre321** [ipashchuk/IP.i4o#4]
I can't find the Nuget package. Does it exist?

thanks

**Comment by ipashchuk** [comment]
Hi,  Harry,

Thanks for your interest. No, I don't have a Nuget package yet. The library
needs a fundamental change to accommodate joins, grouping, and sorting in
addition to the existing filtering support. However, if there is enough
interest in the library as is, I can put it on Nuget.

Thanks.

**Comment by mcintyre321** [comment]
I'll fork it and see it it fits. I've been trying a [few](https://github.com/mcintyre321/Linqdex) [things](https://github.com/mcintyre321/OLinq) to see if I can get db like performance from Linq To Objects, but nothing has quite hit the mark yet...

**Comment by jogibear9988** [comment]
see https://github.com/ipashchuk/IP.i4o

**Comment by jogibear9988** [comment]
see https://github.com/dotnetprojects/IndexedLinq/pull/2

**Comment by ipashchuk** [comment]
Please check out https://github.com/dotnetprojects/IndexedLinq
