### ISSUE TITLE
Exception when an indexed property is null

### ISSUE THREAD

**Issue by marknuzz** [ipashchuk/IP.i4o#6]
When an indexed property is null, an exception will be thrown when updating the indexes.  This occurs at ComparisonIndex.Add(TChild item), line 37 I believe.

**Comment by ipashchuk** [comment]
Thanks for reporting it. Do you think you could create a pull request with a unit test?  I would also be happy to merge the fix.  If not, I'll take a look later.

**Comment by ipashchuk** [comment]
Closing as it's very old.  I recommend https://github.com/dotnetprojects/IndexedLinq that was forked from this repo and has a nuget package.
