### ISSUE TITLE
Why does this library get so little attention?

### ISSUE THREAD

**Issue by pha3z** [ipashchuk/IP.i4o#7]
I came upon the problem that I need to build a generic Dictionary at runtime and I won't know anything about the Key type until I examine the objects I'm working with.  As I started investigating this, I began to think about how many times myself or other developers want indexed collections so they wrap a dictionary or use some other fairly limited built-in collection.  Its unnecessary plumbing code that wastes time. Lo' and behold, I find i4o from another developer looking to solve the same problem but the library is more than 10 years old with barely anybody even knowing about it!!

I certainly didn't see any other libraries when I looked for issues pertaining to LINQ indexing. What's the deal? Is everyone writing plumbing boiler plate all the time because they just don't know better? Is the problem not actually as big of a deal as I think it is? I know I've written a LOT of look-up-style classes in my time, and to me all that reinventing the wheel seems like a big waste. Is everyone reinventing the wheel all the time because its accepted as the norm?

Thoughts?

Hoping I get a reply... :D

**Comment by ipashchuk** [comment]
hi, @pha3z 

I think it has received good attention: there are 24 forks, including https://github.com/dotnetprojects/IndexedLinq, which is now available on nuget.  Check it out!

**Comment by pha3z** [comment]
Oh, so your fork was forked many times.  Woops.  I didn't see that.  I originally found the first library from ericksoa, and I had to go hunting to find your fork, which I didn't see on nuget. Thanks for the reference to IndexLinq.
